# This job is largely lifted from Zizmor (MIT licensed; thanks, William Woodruff!): https://github.com/woodruffw/zizmor/blob/9cd012b752145be6a28ba2e9b9568c139da77b71/.github/workflows/zizmor.yml
name: Zizmor

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  run-zizmor:
    name: Run Zizmor check
    runs-on: ubuntu-latest
    permissions:
      contents: read # to check out the code
      security-events: write # for uploading the SARIF report
      actions: read # to read the workflow files

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          persist-credentials: false

      - name: Set up uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
        with:
          # Enable caching ONLY for PRs within the main repo. Forks do not get cache.
          # uvx will still use a cache within the job, so we don't download Zizmor multiple times.
          enable-cache: ${{ github.repository == github.event.pull_request.head.repo.full_name }}

      - name: Generate SARIF report with Zizmor
        # I don't care about what version of Zizmor is used. Just use the latest; the token is not very strong, anyways.
        run: uvx zizmor --format sarif . | tee results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to GitHub security events
        # If there are security problems, GitHub will automatically comment on the PR for us.
        uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3.29.5
        with:
          sarif_file: results.sarif
          category: zizmor
